config/routes.rb
Rails.application.routes.draw do
  get 'tweets/new'
  resources :users, only: %i[new create edit update show]
  # resource :session
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resource :profile, only: %i[edit update show]

  resources :tweets, only: %i[index new create edit update destroy], shallow: true do
    resources :likes, only: %i[create destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet

  validates :user_id, uniqueness: { scope: :tweet_id }
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user

  validates :content, presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy

  mount_uploader :avater_image, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :login_required

  private
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def login_required
    redirect_to login_path, notice: 'ログインしてください' if current_user.nil?
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    tweet = Tweet.find(params[:tweet_id])
    Like.create(user_id: current_user.id, tweet_id: tweet.id)
    # current_user.likes.create(tweet_id: tweet.id)
    redirect_to tweets_path, notice: 'いいねしました'
  end

  def destroy
    like = current_user.likes.find(params[:id])
    like.destroy!
    redirect_to tweets_path, notice: 'いいねを取り消しました'
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def edit
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(current_user.id)
    if @user.update(user_params)
      redirect_to profile_path, notice: 'ユーザーを更新しました'
    else
      flash.now[:notice] = 'ユーザー更新失敗'
      render :edit
    end
  end

  def show
    @user = User.find(current_user.id)
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: %i[new create]
  def new

  end

  def create
    user = User.find_by(email: session_params[:email])
    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to login_path, notice: 'ログインしました。'
    else
      render :new, notice: 'ログインに失敗しました。'
    end
  end

  def destroy
    reset_session
    redirect_to login_path, notice: 'ログアウトしました。'
  end

  private
  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all.includes(:user)
  end

  def new
    @tweet = current_user.tweets.build
  end

  def create
    @tweet = current_user.tweets.build(tweet_params)
    if @tweet.save
      redirect_to new_tweet_path, notice: 'ツイートを作成しました'
    else
      flash.now[:notice] = 'ツイート作成失敗'
      render :new
    end
  end

  def edit
    @tweet = current_user.tweets.find(params[:id])
  end

  def update
    @tweet = current_user.tweets.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to edit_tweet_path(@tweet), notice: 'ツイートを更新しました'
    else
      flash.now[:notice] = 'ツイート更新失敗'
      render :edit
    end
  end

  def destroy
    @tweet = current_user.tweets.find(params[:id])
    @tweet.destroy!
    redirect_to tweets_path, notice: 'ツイートを削除しました'
  end

  private
  def tweet_params
    params.require(:tweet).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: %i[edit update destroy]
  skip_before_action :login_required, only: %i[new create show]
  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to new_user_path, notice: 'ユーザーを更新しました'
    else
      flash.now[:notice] = 'ユーザー更新失敗'
      render :edit
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_user_path, notice: 'ユーザー登録しました'
    else
      flash.now[:notice] = 'ユーザー登録失敗'
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avater_image)
  end

  def correct_user
    redirect_to new_user_path, notice: '不正なアクセスです' unless current_user.id.to_s == params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Twitterclone
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  body
    .app-title.navbar.navbar-expand-md.navbar-light.bg-light.mb-3
      .navbar-brand#app-title TwitterClone

      ul.navbar-nav.ml-auto
        - if current_user
          li.nav-item= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link'
        - else
          li.nav-item= link_to 'ログイン', login_path, class: 'nav-link'

    - if flash.notice.present?
      .alert.alert-success= flash.notice


    = yield

app/views/profiles/edit.html.slim
.container
  .row
    .col-md-6.col-12.offset-md-3
      .card
        .card-header
          h1
            | ユーザー編集
        .card-body
          - if @user.errors.present?
            ul#error_explanation
              - @user.errors.full_messages.each do |message|
                li= message
          = form_with model: @user, local: true do |f|
            = f.label :name
            = f.text_field :name, class: 'form-control'
            = f.label :email
            = f.email_field :email, class: 'form-control'
            = f.label :password
            = f.password_field :password, class: 'form-control'
            = f.label :password_confirmation
            = f.password_field :password_confirmation, class: 'form-control'
            = f.label :avater_image
            = f.file_field :avater_image, class: 'form-control mb-3'
            = f.submit '更新', class: 'btn btn-primary'

app/views/profiles/show.html.slim
.container
  .row
    .col-md-6.col-12.offset-md-3
      .card
        .card-header
          h1
            | ユーザー詳細
        .card-body
          table.table
            tr
              th Name
              td = @user.name
            tr
              th Email
              td = @user.email

app/views/tweets/_tweet.html.slim
li
  div
    = tweet.user.name
  div.d-flex
    div.mr-3
      div
        = image_tag tweet.user.avater_image_url, size: '50x50', class: 'rounded-circle'
    div.w-100
      div
        = simple_format(tweet.content)
      div.text-right
        = tweet.created_at
  div
    - if current_user.id == tweet.user_id
      = link_to '削除', tweet_path(tweet), method: :delete, class: 'btn btn-danger mr-3', data: { confirm: '削除しますか？' }





    / - like = Like.find_by(user_id: current_user.id, tweet_id: tweet.id)
    / - if like.nil?
    /   = link_to 'いいねする', tweet_likes_path(tweet), class: 'btn btn-success', method: :post
    / - else
    /   = link_to 'いいねを取り消す', like_path(like), class: 'btn btn-danger', method: :delete

  hr

app/views/tweets/edit.html.slim
.container
  .row
    .col-md-6.col-12.offset-md-3
      .card
        .card-header
          h1
            | ツイート編集
        .card-body
          - if @tweet.errors.present?
            ul#error_explanation
              - @tweet.errors.full_messages.each do |message|
                li= message
          = form_with model: @tweet, local: true do |f|
            = f.label :content
            = f.text_area :content, class: 'form-control'
            = f.label :image
            = f.file_field :image, class: 'form-control mb-3'
            = f.submit 'ツイートを編集する', class: 'btn btn-primary'

app/views/tweets/index.html.slim
.container
  .row
    .col-md-6.col-12.offset-md-3
      .card
        .card-header
          h1
            | ツイート一覧
        .card-body
          ul.list-unstyled
            = render @tweets

app/views/tweets/new.html.slim
.container
  .row
    .col-md-6.col-12.offset-md-3
      .card
        .card-header
          h1
            | ツイート作成
        .card-body
          - if @tweet.errors.present?
            ul#error_explanation
              - @tweet.errors.full_messages.each do |message|
                li= message
          = form_with model: @tweet, local: true do |f|
            = f.label :content
            = f.text_area :content, class: 'form-control'
            = f.label :image
            = f.file_field :image, class: 'form-control mb-3'
            = f.submit 'ツイートする', class: 'btn btn-primary'

app/views/users/edit.html.slim
.container
  .row
    .col-md-6.col-12.offset-md-3
      .card
        .card-header
          h1
            | ユーザー編集
        .card-body
          - if @user.errors.present?
            ul#error_explanation
              - @user.errors.full_messages.each do |message|
                li= message
          = form_with model: @user, local: true do |f|
            = f.label :name
            = f.text_field :name, class: 'form-control'
            = f.label :email
            = f.email_field :email, class: 'form-control'
            = f.label :password
            = f.password_field :password, class: 'form-control'
            = f.label :password_confirmation
            = f.password_field :password_confirmation, class: 'form-control mb-3'
            = f.submit '更新', class: 'btn btn-primary'

app/views/users/new.html.slim
.container
  .row
    .col-md-6.col-12.offset-md-3
      .card
        .card-header
          h1
            | ログイン
        .card-body
          - if @user.errors.present?
            ul#error_explanation
              - @user.errors.full_messages.each do |message|
                li= message
          = form_with model: @user, local: true do |f|
            = f.label :name
            = f.text_field :name, class: 'form-control'
            = f.label :email
            = f.email_field :email, class: 'form-control'
            = f.label :password
            = f.password_field :password, class: 'form-control'
            = f.label :password_confirmation
            = f.password_field :password_confirmation, class: 'form-control mb-3'
            = f.submit '登録', class: 'btn btn-primary'

app/views/users/show.html.slim
.container
  .row
    .col-md-6.col-12.offset-md-3
      .card
        .card-header
          h1
            | ユーザー詳細
        .card-body
          table.table
            tr
              th Name
              td = @user.name
            tr
              th Email
              td = @user.email